"""empty message

Revision ID: 215c7333166b
Revises: fca26ecc81b7
Create Date: 2022-01-24 03:50:24.305273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215c7333166b'
down_revision = 'fca26ecc81b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_seats_fkey', 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'seats')
    op.add_column('ticket', sa.Column('id_schedule', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'schedule', ['id_schedule'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'id_schedule')
    op.add_column('schedule', sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('schedule_seats_fkey', 'schedule', 'ticket', ['seats'], ['id'])
    # ### end Alembic commands ###
