"""empty message

Revision ID: 629de7d49777
Revises: 215c7333166b
Create Date: 2022-01-24 04:20:39.899298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629de7d49777'
down_revision = '215c7333166b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'seat',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'ticket', ['seat'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='unique')
    op.alter_column('ticket', 'seat',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
