"""empty message

Revision ID: 8d9a393d95d1
Revises: c60e423e421b
Create Date: 2022-01-30 08:12:18.821066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9a393d95d1'
down_revision = 'c60e423e421b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticket_seat_key', 'ticket', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ticket_seat_key', 'ticket', ['seat'])
    # ### end Alembic commands ###
