"""empty message

Revision ID: 8ec71599fe2d
Revises: 8d9a393d95d1
Create Date: 2022-01-31 04:06:36.328041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec71599fe2d'
down_revision = '8d9a393d95d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cinema_id_movie_fkey', 'cinema', type_='foreignkey')
    op.drop_column('cinema', 'id_movie')
    op.add_column('movie', sa.Column('id_movie', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movie', 'cinema', ['id_movie'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'id_movie')
    op.add_column('cinema', sa.Column('id_movie', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cinema_id_movie_fkey', 'cinema', 'movie', ['id_movie'], ['id'])
    # ### end Alembic commands ###
