"""empty message

Revision ID: a8c471ef0296
Revises: dca0b31c685f
Create Date: 2022-01-31 04:13:27.973581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c471ef0296'
down_revision = 'dca0b31c685f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema', sa.Column('id_movie', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cinema', 'movie', ['id_movie'], ['id'])
    op.drop_constraint('movie_id_cinema_fkey', 'movie', type_='foreignkey')
    op.drop_column('movie', 'id_cinema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('id_cinema', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('movie_id_cinema_fkey', 'movie', 'cinema', ['id_cinema'], ['id'])
    op.drop_constraint(None, 'cinema', type_='foreignkey')
    op.drop_column('cinema', 'id_movie')
    # ### end Alembic commands ###
