"""empty message

Revision ID: c567783bf966
Revises: 629de7d49777
Create Date: 2022-01-24 18:49:15.271573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c567783bf966'
down_revision = '629de7d49777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('released', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'released')
    # ### end Alembic commands ###
