"""empty message

Revision ID: d4108fd3ee0d
Revises: 
Create Date: 2022-01-25 20:31:49.137240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4108fd3ee0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('synopsis', sa.String(length=400), nullable=False),
    sa.Column('genre', sa.String(length=40), nullable=False),
    sa.Column('release_date', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=120), nullable=False),
    sa.Column('released', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cinema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(precision=53), nullable=False),
    sa.Column('longitude', sa.Float(precision=53), nullable=False),
    sa.Column('id_movie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_movie'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('longitude')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_movie', sa.Integer(), nullable=True),
    sa.Column('id_cinema', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('hour', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_cinema'], ['cinema.id'], ),
    sa.ForeignKeyConstraint(['id_movie'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_movie', sa.Integer(), nullable=True),
    sa.Column('id_schedule', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('hour', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('cinema', sa.String(length=80), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('seat', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id_movie'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['id_schedule'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('seat')
    )
    op.create_table('snack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_ticket', sa.Integer(), nullable=True),
    sa.Column('snack', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snack')
    op.drop_table('ticket')
    op.drop_table('schedule')
    op.drop_table('cinema')
    op.drop_table('user')
    op.drop_table('movie')
    op.drop_table('administrator')
    # ### end Alembic commands ###
