"""empty message

Revision ID: fca26ecc81b7
Revises: 
Create Date: 2022-01-24 03:28:39.041392

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'fca26ecc81b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('synopsis', sa.String(length=400), nullable=False),
    sa.Column('genre', sa.String(length=40), nullable=False),
    sa.Column('release_date', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cinema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('latitud', sa.Float(precision=53), nullable=False),
    sa.Column('longitud', sa.Float(precision=53), nullable=False),
    sa.Column('id_movie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_movie'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitud'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('longitud')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_movie', sa.Integer(), nullable=True),
    sa.Column('hour', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('cinema', sa.String(length=80), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('seat', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.ForeignKeyConstraint(['id_movie'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_movie', sa.Integer(), nullable=True),
    sa.Column('id_cinema', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('hour', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_cinema'], ['cinema.id'], ),
    sa.ForeignKeyConstraint(['id_movie'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['seats'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('ticket')
    op.drop_table('cinema')
    op.drop_table('user')
    op.drop_table('movie')
    op.drop_table('administrator')
    # ### end Alembic commands ###
